# Generated by Django 4.2.2 on 2023-06-28 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NuevaApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='compras',
            new_name='comprar',
        ),
        migrations.RenameModel(
            old_name='productos',
            new_name='lista',
        ),
    ]
