# Generated by Django 4.2.2 on 2023-06-28 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NuevaApp', '0002_rename_compras_comprar_rename_productos_lista'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lista',
            new_name='listaJuegos',
        ),
        migrations.RenameModel(
            old_name='comprar',
            new_name='listaPerifericos',
        ),
        migrations.RenameField(
            model_name='listaperifericos',
            old_name='juego',
            new_name='tipo',
        ),
    ]
